// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-tWBdoYK4IFgcsUuDmZyw6_KvD8flU6g',
    appId: '1:915208384030:web:9ff6788dcedcc7569c480f',
    messagingSenderId: '915208384030',
    projectId: 'flutter-chat12842',
    authDomain: 'flutter-chat12842.firebaseapp.com',
    storageBucket: 'flutter-chat12842.appspot.com',
    measurementId: 'G-QLFYJT3Y8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHITZz83PboWPQEnmcJTtpNx1HvJFW6aM',
    appId: '1:915208384030:android:d498603f5d51f5eb9c480f',
    messagingSenderId: '915208384030',
    projectId: 'flutter-chat12842',
    storageBucket: 'flutter-chat12842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcvZc8ijlEbpq7mBZaNfC4_e7nOIex9hE',
    appId: '1:915208384030:ios:c60d85f76b619ee19c480f',
    messagingSenderId: '915208384030',
    projectId: 'flutter-chat12842',
    storageBucket: 'flutter-chat12842.appspot.com',
    iosClientId: '915208384030-dfge8se1d5fqdt8kklqecdiu3tft9urh.apps.googleusercontent.com',
    iosBundleId: 'com.example.module14FirebaseImageUploadPushNotificationsChatApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcvZc8ijlEbpq7mBZaNfC4_e7nOIex9hE',
    appId: '1:915208384030:ios:c60d85f76b619ee19c480f',
    messagingSenderId: '915208384030',
    projectId: 'flutter-chat12842',
    storageBucket: 'flutter-chat12842.appspot.com',
    iosClientId: '915208384030-dfge8se1d5fqdt8kklqecdiu3tft9urh.apps.googleusercontent.com',
    iosBundleId: 'com.example.module14FirebaseImageUploadPushNotificationsChatApps',
  );
}
